start on making it work on our device

diff --git a/remarkable-postinst b/remarkable-postinst
--- a/remarkable-postinst
+++ b/remarkable-postinst
@@ -90,53 +90,28 @@ elif [[ -z "${INSTALL_KERNEL}" ]]; then
        "${ESP_MNT}/remarkable/vmlinuz-${SLOT,,}"
 fi
 
-# If the OEM provides a hook, call it
-if [[ -x "${OEM_MNT}/bin/oem-postinst" ]]; then
-    "${OEM_MNT}/bin/oem-postinst" "${SLOT}" "${INSTALL_MNT}"
-fi
-
-# locksmith 0.1.5 is broken, restart it lots to work around the issue
-if systemctl is-active --quiet locksmithd.service && \
-    locksmithctl help | grep -A1 '^VERSION:' | grep -q '0.1.5$';
-then
-    echo "Broken locksmith 0.1.5 detected, installing workaround timer."
-    # In one minute start restarting locksmithd every 5 minutes.
-    cat >/run/systemd/system/locksmithd-kicker.timer <<EOF
-[Timer]
-OnActiveSec=1min
-OnUnitActiveSec=5min
-EOF
-    cat >/run/systemd/system/locksmithd-kicker.service <<EOF
-[Service]
-Type=oneshot
-ExecStart=/usr/bin/systemctl try-restart --no-block locksmithd.service
-EOF
-    systemctl start --no-block locksmithd-kicker.timer
-fi
-
-# Azure's agent erroneously looks at the distribution name instead of its ID.
-# This prevents us from renaming the OS from "CoreOS". This patches platform.py
-# to always return "CoreOS" as the distribution name.
-PLATFORM_PATH="/usr/share/oem/python/lib64/python2.7/platform.py"
-if [ -e ${PLATFORM_PATH} ]; then
-    sum=($(md5sum ${PLATFORM_PATH}))
-    if [ ${sum} == "6315addf42c0b07f5f78d119b578e20a" ]; then
-        sed --in-place \
-            "s%distname = os_release_info\['NAME'\]%distname = \"reMarkable\"%" \
-            ${PLATFORM_PATH}
-    fi
-fi
-
-# use the cgpt binary from the image to ensure compatibility
-CGPT=
+# use the fw_setenv binary from the image to ensure compatibility
+FW_SETENV=
 for bindir in bin/old_bins bin sbin; do
-    if [[ -x "${INSTALL_MNT}/${bindir}/cgpt" ]]; then
-        CGPT="${INSTALL_MNT}/${bindir}/cgpt"
+    if [[ -x "${INSTALL_MNT}/${bindir}/fw_setenv" ]]; then
+        FW_SETENV="${INSTALL_MNT}/${bindir}/fw_setenv"
         break
     fi
 done
-if [[ -z "${CGPT}" ]]; then
-    echo "Failed to locate the cgpt binary in ${INSTALL_MNT}" >&2
+if [[ -z "${FW_SETENV}" ]]; then
+    echo "Failed to locate the fw_setenv binary in ${INSTALL_MNT}" >&2
+    exit 1
+fi
+
+FW_PRINTENV=
+for bindir in bin/old_bins bin sbin; do
+    if [[ -x "${INSTALL_MNT}/${bindir}/fw_printenv" ]]; then
+        FW_PRINTENV="${INSTALL_MNT}/${bindir}/fw_printenv"
+        break
+    fi
+done
+if [[ -z "${FW_PRINTENV}" ]]; then
+    echo "Failed to locate the fw_printenv binary in ${INSTALL_MNT}" >&2
     exit 1
 fi
 
@@ -154,15 +129,22 @@ if [[ -z "${LDSO}" ]]; then
 fi
 LIBS="${LDSO%/*}"
 
-call_cgpt() {
-    "${LDSO}" --library-path "${LIBS}" "${CGPT}" "$@"
+call_fw_setenv() {
+    "${LDSO}" --library-path "${LIBS}" "${FW_SETENV}" -c "${INSTALL_MNT}/etc/fw_env.config" "$@"
+}
+call_fw_printenv() {
+    "${LDSO}" --library-path "${LIBS}" "${FW_PRINTENV}" -c "${INSTALL_MNT}/etc/fw_env.config" "$@"
 }
 
-# Mark the new install with one try and the highest priority
-call_cgpt repair "${INSTALL_DEV}"
-call_cgpt add -S0 -T1 "${INSTALL_DEV}"
-call_cgpt prioritize "${INSTALL_DEV}"
-call_cgpt show "${INSTALL_DEV}"
+call_fw_setenv "upgrade_available" "1"
+
+OLDROOT=$(call_fw_printenv -n mmcroot)
+if [[ "${OLDROOT}" == "${INSTALL_DEV}" ]]; then
+    echo "WARNING: We're installing over our current root"
+else
+    call_fw_setenv "mmcfallbackroot" "${OLDROOT}"
+    call_fw_setenv "mmcroot" "${INSTALL_DEV}"
+fi
 
 cat "${INSTALL_MNT}/share/remarkable/release"
 echo "Setup ${INSTALL_LABEL} (${INSTALL_DEV}) for next boot."
